### PR TITLE
Log success and errors to Slack based on env configuration

### LINKED ISSUE #2: Log upload success and failure to Slack
Three environment variables:

* `SLACK_WEBHOOK_URL`
* `SLACK_CHANNEL_SUCCESS` - Reporting successful uploads
* `SLACK_CHANNEL_ERROR` - Reporting errored uploads, and other error statuses

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #2

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@mpatek #reviewmerge ?

**Comment by mpatek** [comment]
@danielbachhuber this looks fine. Might be neat to create a [Logger Object](https://docs.python.org/2/library/logging.html#logger-objects) that can send messages to Slack.

**Comment by mpatek** [comment]
Actually, it would make more sense to build a Slack logging handler, and then add it to the logger. Looks like this [already exists](https://github.com/loisaidasam/pyslack#usage)

**Comment by danielbachhuber** [comment]
> Actually, it would make more sense to build a Slack logging handler, and then add it to the logger. Looks like this already exists

I'm not (yet) piping all log messages into Slack, only the critical ones. But, good suggestion to consider later.

**Pull request merged**
